name = radar_atc
description = Radar ATC — Surveillance aérienne, gestion d'aéroports et contrôle du trafic aérien pour le mod laptop. Nécessite laptop et airutils.
depends = laptop, airutils
min_minetest_version = 5.4
