name = radar_atc
title = Radar ATC
author = Luffy0805
description = Radar ATC — Surveillance aérienne, gestion d'aéroports et contrôle du trafic aérien pour le mod laptop. Nécessite laptop et airutils.
depends = laptop, airutils, default
min_minetest_version = 5.4
version = 1.0.0
license = MIT
media_license = CC BY-SA 4.0
