name = radar_atc
title = Radar / ATC
author = Luffy0805
description = Application Radar ATC pour le mod laptop. Surveillance aérienne, gestion d'aéroports et communication ATC. Nécessite laptop et airutils.
depends = laptop, airutils
min_minetest_version = 5.4
version = 0.5
